name: main
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Go1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Checkout
      uses: actions/checkout@v1

    - name: Dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make build
