# Force push to 'prerelease' to get a JS/docker build for testing etc
name: prerelease
on:
  push:
    branches:
      - prerelease
    tags-ignore:
      - 'v*'

jobs:
  js:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow --prune
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}"
          make publish_js

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make docker_build
      - name: publish monax
        env:
          DOCKER_REPO: "hyperledger/burrow"
          DOCKER_REPO_DEV: "quay.io/monax/burrow"
          DOCKER_PASS_DEV: ${{ secrets.DOCKER_PASS_DEV }}
          DOCKER_USER_DEV: ${{ secrets.DOCKER_USER_DEV }}
        run: |
          version=$(./scripts/local_version.sh)
          echo ${DOCKER_PASS_DEV} | docker login --username ${DOCKER_USER_DEV} ${DOCKER_REPO_DEV} --password-stdin
          docker tag ${DOCKER_REPO}:${version} ${DOCKER_REPO_DEV}:${version}
          docker push --all-tags ${DOCKER_REPO_DEV}
      - name: publish hyperledger
        env:
          DOCKER_REPO: "hyperledger/burrow"
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          version=$(./scripts/local_version.sh)
          echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin
          docker tag ${DOCKER_REPO}:${version} ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO}:latest
